# Generated by Django 4.0.4 on 2022-05-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_track_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='uri',
            field=models.CharField(default='', max_length=100),
        ),
    ]
