# Generated by Django 4.0.3 on 2022-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='artists',
            field=models.ManyToManyField(related_name='libraries', to='artists.artist'),
        ),
    ]
