# Generated by Django 4.0.3 on 2022-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
