# Generated by Django 4.0.4 on 2022-05-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='spotify_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
