# Generated by Django 4.0.3 on 2022-04-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'spotify_id',
                    models.CharField(max_length=22, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'artists',
                    models.ManyToManyField(related_name='albums', to='artists.artist'),
                ),
            ],
        ),
    ]
