# Generated by Django 4.0.4 on 2022-05-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
