# Generated by Django 4.0.3 on 2022-04-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                (
                    'spotify_id',
                    models.CharField(max_length=22, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=200)),
                ('duration_ms', models.CharField(max_length=6)),
                ('is_explicit', models.BooleanField(default=False)),
                ('popularity', models.CharField(max_length=3)),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='albums.album',
                    ),
                ),
                (
                    'artists',
                    models.ManyToManyField(related_name='tracks', to='artists.artist'),
                ),
            ],
        ),
    ]
