# Generated by Django 4.0.3 on 2022-03-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ForeignKey(
                default='NOT ADDED',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tracks',
                to='artists.artist',
            ),
            preserve_default=False,
        ),
    ]
