# Generated by Django 4.0.4 on 2022-04-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration_ms',
        ),
        migrations.AddField(
            model_name='track',
            name='_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
