# Generated by Django 4.0.4 on 2022-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.CharField(max_length=7),
        ),
    ]
