# Generated by Django 4.0.4 on 2022-04-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_duration_ms_track__duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='_duration',
            new_name='_duration_ms',
        ),
    ]
