# Generated by Django 4.0.3 on 2022-03-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('tracks', '0003_remove_track_artists_track_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(
                default='NOT ADDED',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tracks',
                to='albums.album',
            ),
        ),
    ]
