# Generated by Django 4.0.4 on 2022-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_rename__duration_track__duration_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='_duration_ms',
        ),
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
