# Generated by Django 4.0.4 on 2022-04-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_track__duration_ms_track_duration_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
