# Generated by Django 4.0.3 on 2022-03-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('tracks', '0004_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AddField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tracks',
                to='albums.album',
            ),
        ),
    ]
