# Generated by Django 4.0.3 on 2022-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'tracks',
            '0005_track_duration_ms_track_is_explicit_track_popularity_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='popularity',
            field=models.CharField(max_length=3),
        ),
    ]
