# Generated by Django 4.0.3 on 2022-04-06 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_alter_track_duration_ms_alter_track_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='duration_ms',
            new_name='_duration_ms',
        ),
    ]
