name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.Heroku_API_KEY}}
          heroku_app_name: "my-spotify-tool"
          heroku_email: "derekjamerson@gmail.com"
